### ISSUE TITLE
Move repository to https://github.com/apache/incubator-zipkin-api

### ISSUE THREAD

**Issue by michaelsembwever** [apache/incubator-zipkin-api#53]
As part of the move to the Apache Software Foundation this repository will transfer ownership to `apache` and name to `incubator-zipkin-api`.

See https://issues.apache.org/jira/browse/INFRA-16989

**Comment by flixr** [comment]
Seems this is done, but the link https://zipkin.io/zipkin-api/ doesn't work anymore...

**Comment by jeqo** [comment]
@flixr could you try https://zipkin.apache.org/zipkin-api/ ?

**Comment by flixr** [comment]
thx, that works
