### ISSUE TITLE
broke

### ISSUE THREAD

**Issue by adriancole** [apache/incubator-zipkin-api#62]
@zhouyaohua noticed after the ASF move the zipkin uri is busted https://zipkin.io/zipkin-api/#/default/get_services

I assume this is related to the move, but we also merged a change recently to the swagger

**Comment by adriancole** [comment]
@abesto can you save us?

**Comment by adriancole** [comment]
most extreme bat signal https://lists.apache.org/thread.html/3faf9d2f40108ffe8923f88d81ef9afe39f1bae0e08048b4da95fa19@%3Cdev.zipkin.apache.org%3E

**Comment by abesto** [comment]
Well crap, not sure how I missed this. Checking now.

**Comment by abesto** [comment]
Sooo here's what's up.

Originally this repo was `openzipkin/zipkin-api`, configured to be served via GitHub pages. GH maps `openzipkin/zipkin-api` to `openzipkin.github.io/zipkin-api`, and so things were good (including with the custom domain `zipkin.io`). Once the repo moved to under `apache`, this mapping of course broke.

My immediate band-aid was copying the contents into `openzipkin/openzipkin.github.io`, to the folder `zipkin-api`. This means the contents can now be reached, except `index.html` **MUST** be supplied now, as GH Pages only does automatic `index.html` resolution at the root of each repository, which this has now stopped being.

So this means any URL `https://zipkin.io/zipkin-api/$1` is now available at `https://zipkin.io/zipkin-api/index.html$1`. Case in point, for the URL in the original report, https://zipkin.io/zipkin-api/index.html#/default/get_services is now available. Unfortunately I don't see a way of making the URL work as it did before. Plus, I think the effort we'd spend looking for workarounds to get rid of the explicit `index.html` is better spent on migrating to `zipkin.apache.org`.

@adriancole I'll leave this open so any user-facing communication or whatever else can be tracked here.

**Comment by abesto** [comment]
Huh, weird. Meanwhile https://zipkin.io/zipkin-api/#/default/get_services came back, so I guess `index.html` just took a bit to propagate to the home-page. That means this is now fully mitigated with no need for user-facing communication. Closing.
