### ISSUE TITLE
decide if we want to validate thrift on pull request or not

### ISSUE THREAD

**Issue by adriancole** [apache/incubator-zipkin-api#69]
Unlike swagger and proto, there's no pure javascript tool to validate or use thrifts. You have to rely on a OS binary to first generate the code. This means our travis config either has to invoke two tools or we have a binary dependency in our [validate.test.js](https://github.com/apache/incubator-zipkin-api/blob/master/validate.test.js) only for thrift.

another option is to simply not bother with thrift checking as we don't add anything to it anymore.

cc @apache/zipkin-committers

**Comment by adriancole** [comment]
fwiw we've never validated thrift on pull request, and incidentally until today even swagger validation was busted!

Now, we validate swagger and proto on pull request.

**Comment by jcchavezs** [comment]
I would not add validation for now as we are not changing it. Even if
change I would not try to validate or until the necessity of a big change.

tir. 30. apr. 2019, 05:39 skrev Adrian Cole <notifications@github.com>:

**Comment by jeqo** [comment]
I'm with @jcchavezs, if we don't add anything to thrift anymore, we should not add validation.

**Comment by adriancole** [comment]
rule of three
